name: Build CI

on:
  push:
    branches: [ island-time-only ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#     - name: Decode google-services.json
#       env:
#         FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
#       run: echo $FIREBASE_CONFIG > AndroidApp/google-services.json
    - name: Build 
      run: ./gradlew build
    - name: Pack for xCode
      run: ./gradlew packForXCode
